- name: Checking if AUFS is installed
  command: grep aufs /proc/filesystems
  register: dokku_aufs_installed 
  ignore_errors: yes
  failed_when: dokku_aufs_installed.rc == 1 
  when: dokku_ignore_aufs == false

- name: AUFS is not installed
  pause:
    prompt:
      - "Continue install without AUFS?"
  when: not dokku_ignore_aufs and dokku_aufs_installed.rc == 1 

# - name: Enable https apt repositories
  # become: yes
  # apt:
    # name: apt-transport-https

- name: Add dokku repository key
  become: yes
  apt_key:
    url: https://packagecloud.io/gpg.key

- name: Add dokku apt repository
  become: yes
  apt_repository: 
    repo: deb https://packagecloud.io/dokku/dokku/ubuntu/ trusty main
    filename: dokku
    update_cache: yes

- name: Install dokku
  become: yes
  apt:
    name: "dokku={{ dokku_version }}"
    install_recommends: "{{ dokku_install_recommends }}"

- name: Install dokku plugins
  become: yes
  command: "dokku plugin:install {{ item.repo }}"
  with_items: "{{ dokku_plugins }}"
